### ISSUE TITLE
First run of demo service (helloworldclient) fails to connect

### ISSUE THREAD

**Issue by mwyzhao** [Multi-Tier-Cloud/service-manager#8] opened 2020-03-01 09:16 UTC
Proxy fails to connect to helloworldserver running at 10.11.17.10:8080 first time it is requested by helloworldclient.
- Error message: "http: panic serving 127.0.0.1:38830: Get http://10.11.17.10:8080/: dial tcp 10.11.17.10:8080: connect: connection refused"
- Runs fine after "curl 127.0.0.1:8080" is run

**Comment by t-lin** [comment] 2020-03-01 16:52
Do you think this is the same issue as before? (i.e. network flows take too long to set up the first time, so it fails)

**Comment by mwyzhao** [comment] 2020-03-02 01:48
It doesn't look like it times out, just immediately fails. Curl always seems to work no matter what if I recall correctly. I can do some more testing after some of the more priority stuff is done.

**Comment by t-lin** [comment] 2020-06-13 22:08
I'm closing this for now since I havn't seen any behaviour like this.
We can re-open it if the same (or similar) behaviour occurs again, and/or if we figure out how to reproduce this behaviour.

**Closed as completed by t-lin** 2020-06-13 22:08 UTC
Labels: bug, investigate
